### PR TITLE
Restore possibility to run without mainloop

### PR DESCRIPTION
**Pull request by AndersBlomdell**
Addresses #84 and #66

### CODE REVIEW

**Comment by xvitaly** [comment]
@seveas Can you review and merge this patch?

**Comment by Hadatko** [comment]
We had to use version mentioned here: https://github.com/seveas/python-networkmanager/issues/84#issuecomment-802491160 as this patch is not applied.

**Comment by Hadatko** [comment]
> > We had to use version mentioned here: #84 (comment) as this patch is not applied.
> 
> Version 2.1 has some major compatibility issues with the modern Network Manager.

Could be but for our case it is working well

**Comment by maggie0002** [comment]
> > We had to use version mentioned here: #84 (comment) as this patch is not applied.
> 
> Version 2.1 has some major compatibility issues with the modern Network Manager.

What sort of compatibility issues? Isn't it just adding in some new types of device? https://github.com/seveas/python-networkmanager/commit/c4a5913da45a2ce427c141f4e9df57199f34083e. If not using those new device types, is there any differences?

**Comment by xvitaly** [comment]
> What sort of compatibility issues? Isn't it just adding in some new types of device?

Yes.

> If not using those new device types, is there any differences?

It will instantly crash. See #68 and #76.

**Comment by maggie0002** [comment]
> > What sort of compatibility issues? Isn't it just adding in some new types of device?
> 
> Yes.
> 
> > If not using those new device types, is there any differences?
> 
> It will instantly crash. See #68 and #76.

Eek, ok so even if you’re not using those new devices, if they exist then you can’t fetch and use other devices. Does make downgrading back to 2.1 risky.

**Comment by maggie0002** [comment]
A cheeky bump here in the new year, hoping we can merge this. ☺️

**Review by bernhardkaindl — APPROVED** [review]
Works here, please merge!

**Comment by xvitaly** [comment]
The project is dead. Someone need to fork it.

**Comment by seveas** [comment]
It's been on life support for a while. I've been trying to find someone with the right skills and willingness to take over, but with no success so far.

**Comment by bernhardkaindl** [comment]
@seveas Well, you should state it in the project's README.md, otherwise nobody will ever know and assume it was just deserted.

You could at least merge it, one year of having an independent confirmation that this PR does indeed work would be about time.

Also, it would be good to add the info that it's dead and forking is appreciated and in the README, you could, also add a list of better alternatives such as:
https://github.com/python-sdbus/python-sdbus-networkmanager

In the new 2.0rc1, it has new helper classes for easy reading of NetworkManager connection profile settings, with a nice interface to update them as well. It's used in production too.

**Comment by seveas** [comment]
Happy to hear there are alternatives these days, I'll just archive this repo then.

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.

**Pull request closed without merging**
